name: Run every 24 hours

on:
  schedule:
    - cron: '* */24 * * *' 
  workflow_dispatch:  # This allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest  # You can change this to the OS you prefer

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Use the desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # If you have a requirements file

      - name: Run the script
        run: |
          python app.py  # Replace with your script name

      - name: Set up Git for pushing changes
        run: |
          git config --global user.name "aszzc"
          git config --global user.email "aszzc@users.noreply.github.com"

      - name: Commit and push generated files
        run: |
          git add v2ray.txt  # Add your generated files
          git commit -m "Update generated config files" || echo "No changes to commit"
          git push origin HEAD  # Push the changes to the same branch
